import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Providers from './providers';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

const pretandard = localFont({
  src: '../public/Pretendard-Variable.woff2',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${pretandard.className} antialiased `}>
        <Providers>
          {children}
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
